using System;
using System.Collections.Generic;

namespace BroadwayNextWeb.Models
{
    public class VendorsSearch
    {
        public int RecNo { get; set; }
        public string MAC { get; set; }
        public Nullable<int> Vendnum { get; set; }
        public string Company { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string DBA { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Emergency { get; set; }
        public string Mobile { get; set; }
        public string Contact { get; set; }
        public Nullable<bool> ActiveType { get; set; }
        public Nullable<bool> W9 { get; set; }
        public string GLnum { get; set; }
        public string ADPnum { get; set; }
        public Nullable<int> NetDays { get; set; }
        public string TaxID { get; set; }
        public Nullable<decimal> Tax1099 { get; set; }
        public Nullable<bool> Tax1099YN { get; set; }
        public Nullable<int> TermDay { get; set; }
        public string Terms { get; set; }
        public Nullable<decimal> TermDiscount { get; set; }
        public string VendorType { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public string WebUsername { get; set; }
        public string WebPassword { get; set; }
        public string Insurance1 { get; set; }
        public string Policy1 { get; set; }
        public Nullable<System.DateTime> ExpDate1 { get; set; }
        public Nullable<decimal> Limit1 { get; set; }
        public Nullable<bool> Exempt1 { get; set; }
        public Nullable<bool> Insured1 { get; set; }
        public string Insurance2 { get; set; }
        public string Policy2 { get; set; }
        public Nullable<System.DateTime> ExpDate2 { get; set; }
        public Nullable<decimal> Limit2 { get; set; }
        public Nullable<bool> Exempt2 { get; set; }
        public Nullable<bool> Insured2 { get; set; }
        public string Insurance3 { get; set; }
        public string Policy3 { get; set; }
        public Nullable<System.DateTime> ExpDate3 { get; set; }
        public Nullable<decimal> Limit3 { get; set; }
        public Nullable<bool> Exempt3 { get; set; }
        public Nullable<bool> Insured3 { get; set; }
        public Nullable<System.DateTime> TerminatedDate { get; set; }
        public Nullable<System.DateTime> TerminatedEffDate { get; set; }
        public string TerminatedReason { get; set; }
        public string TerminatedBy { get; set; }
        public string Rehire { get; set; }
        public string Grade { get; set; }
        public string CheckCompany { get; set; }
        public string CheckAddress1 { get; set; }
        public string CheckAddress2 { get; set; }
        public string CheckCity { get; set; }
        public string CheckState { get; set; }
        public string CheckZip { get; set; }
        public string CheckContact { get; set; }
        public string CheckPhone { get; set; }
        public string ShipCompany { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipZip { get; set; }
        public string ShipContact { get; set; }
        public string ShipPhone { get; set; }
        public string Recruiter { get; set; }
        public string ReferBy { get; set; }
        public string FactorCompany { get; set; }
        public string FactorAddress1 { get; set; }
        public string FactorAddress2 { get; set; }
        public string FactorCity { get; set; }
        public string FactorState { get; set; }
        public string FactorZip { get; set; }
        public string FactorPhone { get; set; }
        public string FactorFax { get; set; }
        public string FactorContact { get; set; }
        public Nullable<System.DateTime> Inputdate { get; set; }
        public string Inputby { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Comment1 { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<int> ServiceCnt { get; set; }
        public string drivingtime { get; set; }
        public Nullable<bool> Dormant { get; set; }
        public Nullable<decimal> RateInt { get; set; }
        public Nullable<decimal> RateExt { get; set; }
        public string Province { get; set; }
        public string EmailAutoFax { get; set; }
        public Nullable<int> PriceCnt { get; set; }
        public Nullable<int> NP { get; set; }
        public Nullable<int> SC { get; set; }
        public Nullable<int> LP { get; set; }
        public Nullable<int> SV { get; set; }
        public Nullable<int> TermSV { get; set; }
        public Nullable<int> TermLP { get; set; }
        public Nullable<int> TermNP { get; set; }
        public Nullable<int> TermSC { get; set; }
        public Nullable<bool> SignedContract { get; set; }
        public Nullable<bool> VPA { get; set; }
        public Nullable<bool> InsuranceWaiver { get; set; }
        public string InsuranceWaiverReason { get; set; }
    }
}
